version: '3'
services:
  postgres:
    image: postgres:16.2
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgresdata:/var/lib/postgresql/data

volumes:
  postgresdata: